# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: ['push', 'pull_request']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 11.x

      - name: yarn install, yarn test
        run: |
          yarn --frozen-lockfile
          yarn build:parser
          yarn test --coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
